# Generated by Django 4.0.4 on 2022-05-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='csvc',
            name='ban_ghe',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='csvc',
            name='den',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='csvc',
            name='dieu_hoa',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='csvc',
            name='may_chieu',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='csvc',
            name='quat',
            field=models.IntegerField(default=4),
        ),
    ]
