# Generated by Django 4.0.4 on 2022-05-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvc', '0002_department_alter_csvc_ban_ghe_alter_csvc_den_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvc',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csvc.department'),
        ),
    ]
